services:

  db-health:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    environment:
      SQLCMDPASSWORD: "${DB_SA_PASSWORD}"
    entrypoint:
      - /bin/bash
      - -c
      - |
        until /opt/mssql-tools/bin/sqlcmd \
          -S db,1433 \
          -U sa \
          -Q "SELECT 1" \
          -b -l 3 >/dev/null 2>&1; do
          echo "Waiting for SQL Server..."
          sleep 3
        done
        echo "SQL Server is ready."
    restart: "no"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${DB_SA_PASSWORD}"

    ports:
      - "1434:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: GeneralPurposeApplication.Server/Dockerfile

    depends_on:
      db-health:
        condition: service_completed_successfully

    ports:
      - "8080:8080"

    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=GeneralPurposeApplication;User Id=sa;Password=${DB_SA_PASSWORD};Integrated Security=False;MultipleActiveResultSets=True;TrustServerCertificate=True"

      JwtSettings__Issuer: "12345678-Grandpa"
      JwtSettings__Audience: "12345678-Grandpa-Users"
      JwtSettings__ExpirationTimeInMinutes: "60"
      JwtSettings__SecurityKey: "${JWT_SECURITY_KEY}"

      DefaultPasswords__RegisteredUser: "${DEFAULT_PASSWORD_USER}"
      DefaultPasswords__Administrator: "${DEFAULT_PASSWORD_ADMIN}"

  frontend:
    build:
      context: ./GeneralPurposeApplication.Client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  sqlserver_data: